export const songs = [
  {
    songIndex: "1",
    songName: "Et c'est pour ca",
    mp3: "https://www.creapiks.net/BlindTest/1.mp3",
    album: "1",
  },
  {
    songIndex: "2",
    songName: "La tartiflette",
    mp3: "https://www.creapiks.net/BlindTest/2.mp3",
    album: "1",
  },
  {
    songIndex: "3",
    songName: "Les routes de Nantes",
    mp3: "https://www.creapiks.net/BlindTest/3.mp3",
    album: "1",
  },
  {
    songIndex: "4",
    songName: "Arthur",
    mp3: "https://www.creapiks.net/BlindTest/4.mp3",
    album: "1",
  },
  {
    songIndex: "5",
    songName: "Je suis moche",
    mp3: "https://www.creapiks.net/BlindTest/5.mp3",
    album: "1",
  },
  {
    songIndex: "6",
    songName: "Je te trouve tellement jolie",
    mp3: "https://www.creapiks.net/BlindTest/6.mp3",
    album: "1",
  },

  {
    songIndex: "7",
    songName: "Le Père Noel",
    mp3: "https://www.creapiks.net/BlindTest/7.mp3",
    album: "1",
  },
  {
    songIndex: "8",
    songName: "Que j'aime tes fesses",
    mp3: "https://www.creapiks.net/BlindTest/8.mp3",
    album: "1",
  },
  {
    songIndex: "9",
    songName: "Mon rêve",
    mp3: "https://www.creapiks.net/BlindTest/9.mp3",
    album: "1",
  },
  {
    songIndex: "10",
    songName: "Tu pues la crotte",
    mp3: "https://www.creapiks.net/BlindTest/10.mp3",
    album: "1",
  },
  {
    songIndex: "11",
    songName: "Le ver",
    mp3: "https://www.creapiks.net/BlindTest/11.mp3",
    album: "1",
  },
  {
    songIndex: "12",
    songName: "La cousine",
    mp3: "https://www.creapiks.net/BlindTest/12.mp3",
    album: "1",
  },
  {
    songIndex: "13",
    songName: "J'aime pas la viande cuite",
    mp3: "https://www.creapiks.net/BlindTest/13.mp3",
    album: "1",
  },
  {
    songIndex: "14",
    songName: "Heavy Metal",
    mp3: "https://www.creapiks.net/BlindTest/14.mp3",
    album: "1",
  },

  {
    songIndex: "15",
    songName: "Cheese Powers",
    mp3: "https://www.creapiks.net/BlindTest/15.mp3",
    album: "2",
  },
  {
    songIndex: "16",
    songName: "De Cannes à Nice",
    mp3: "https://www.creapiks.net/BlindTest/16.mp3",
    album: "2",
  },
  {
    songIndex: "17",
    songName: "Sombre héros",
    mp3: "https://www.creapiks.net/BlindTest/17.mp3",
    album: "2",
  },
  {
    songIndex: "18",
    songName: "Anal Satellite",
    mp3: "https://www.creapiks.net/BlindTest/18.mp3",
    album: "2",
  },
  {
    songIndex: "19",
    songName: "Emmène-moi là-bas",
    mp3: "https://www.creapiks.net/BlindTest/19.mp3",
    album: "2",
  },
  {
    songIndex: "20",
    songName: "Ma botte au cul",
    mp3: "https://www.creapiks.net/BlindTest/20.mp3",
    album: "2",
  },
  {
    songIndex: "21",
    songName: "La Ferme",
    mp3: "https://www.creapiks.net/BlindTest/21.mp3",
    album: "2",
  },
  {
    songIndex: "22",
    songName: "Ma cigarette",
    mp3: "https://www.creapiks.net/BlindTest/22.mp3",
    album: "2",
  },
  {
    songIndex: "23",
    songName: "La Wave Attitude",
    mp3: "https://www.creapiks.net/BlindTest/23.mp3",
    album: "2",
  },
  {
    songIndex: "24",
    songName: "J'ai une histoire triste",
    mp3: "https://www.creapiks.net/BlindTest/24.mp3",
    album: "2",
  },
  {
    songIndex: "25",
    songName: "Je mange déséquilibré",
    mp3: "https://www.creapiks.net/BlindTest/25.mp3",
    album: "2",
  },
  {
    songIndex: "26",
    songName: "Marie",
    mp3: "https://www.creapiks.net/BlindTest/26.mp3",
    album: "2",
  },
  {
    songIndex: "27",
    songName: "Ma raison d'être",
    mp3: "https://www.creapiks.net/BlindTest/27.mp3",
    album: "2",
  },

  {
    songIndex: "28",
    songName: "Ça nous saoule",
    mp3: "https://www.creapiks.net/BlindTest/28.mp3",
    album: "3",
  },
  {
    songIndex: "29",
    songName: "Lettre à Michelle",
    mp3: "https://www.creapiks.net/BlindTest/29.mp3",
    album: "3",
  },
  {
    songIndex: "30",
    songName: "BB Rockers",
    mp3: "https://www.creapiks.net/BlindTest/30.mp3",
    album: "3",
  },
  {
    songIndex: "31",
    songName: "J'ai un bon copain",
    mp3: "https://www.creapiks.net/BlindTest/31.mp3",
    album: "3",
  },
  {
    songIndex: "32",
    songName: "Trouvez-vous ça bien",
    mp3: "https://www.creapiks.net/BlindTest/32.mp3",
    album: "3",
  },
  {
    songIndex: "33",
    songName: "La galère d'un pirate",
    mp3: "https://www.creapiks.net/BlindTest/33.mp3",
    album: "3",
  },
  {
    songIndex: "34",
    songName: "Et à la fin.",
    mp3: "https://www.creapiks.net/BlindTest/34.mp3",
    album: "3",
  },
  {
    songIndex: "35",
    songName: "La base virale",
    mp3: "https://www.creapiks.net/BlindTest/35.mp3",
    album: "3",
  },
  {
    songIndex: "36",
    songName: "À la chasse",
    mp3: "https://www.creapiks.net/BlindTest/36.mp3",
    album: "3",
  },
  {
    songIndex: "37",
    songName: "Allons chez toi",
    mp3: "https://www.creapiks.net/BlindTest/37.mp3",
    album: "3",
  },
  {
    songIndex: "38",
    songName: "Une histoire formidable",
    mp3: "https://www.creapiks.net/BlindTest/38.mp3",
    album: "3",
  },
  {
    songIndex: "39",
    songName: "Nirvanoir",
    mp3: "https://www.creapiks.net/BlindTest/39.mp3",
    album: "3",
  },
  {
    songIndex: "40",
    songName: "Car tu es",
    mp3: "https://www.creapiks.net/BlindTest/40.mp3",
    album: "3",
  },

  {
    songIndex: "41",
    songName: "L'amour de la musique",
    mp3: "https://www.creapiks.net/BlindTest/41.mp3",
    album: "4",
  },
  {
    songIndex: "42",
    songName: "Babos à la Playa",
    mp3: "https://www.creapiks.net/BlindTest/42.mp3",
    album: "4",
  },
  {
    songIndex: "43",
    songName: "Je suis covoiturage",
    mp3: "https://www.creapiks.net/BlindTest/43.mp3",
    album: "4",
  },
  {
    songIndex: "44",
    songName: "C'est pas punk",
    mp3: "https://www.creapiks.net/BlindTest/44.mp3",
    album: "4",
  },
  {
    songIndex: "45",
    songName: "Ça plane pour moi",
    mp3: "https://www.creapiks.net/BlindTest/45.mp3",
    album: "4",
  },
  {
    songIndex: "46",
    songName: "Bienvenue à bord",
    mp3: "https://www.creapiks.net/BlindTest/46.mp3",
    album: "4",
  },
  {
    songIndex: "47",
    songName: "Beauf de France",
    mp3: "https://www.creapiks.net/BlindTest/47.mp3",
    album: "4",
  },
  {
    songIndex: "48",
    songName: "Génération 90's",
    mp3: "https://www.creapiks.net/BlindTest/48.mp3",
    album: "4",
  },
  {
    songIndex: "49",
    songName: "Subjectif",
    mp3: "https://www.creapiks.net/BlindTest/49.mp3",
    album: "4",
  },
  {
    songIndex: "50",
    songName: "Cougar",
    mp3: "https://www.creapiks.net/BlindTest/50.mp3",
    album: "4",
  },
  {
    songIndex: "51",
    songName: "Escuala mi amor",
    mp3: "https://www.creapiks.net/BlindTest/51.mp3",
    album: "4",
  },
  {
    songIndex: "52",
    songName: "La nouvelle star",
    mp3: "https://www.creapiks.net/BlindTest/52.mp3",
    album: "4",
  },
  {
    songIndex: "53",
    songName: "J'te tire",
    mp3: "https://www.creapiks.net/BlindTest/53.mp3",
    album: "4",
  },
  {
    songIndex: "54",
    songName: "Bonus 8 bits",
    mp3: "https://www.creapiks.net/BlindTest/54.mp3",
    album: "4",
  },

  {
    songIndex: "55",
    songName: "Ouvre les yeux",
    mp3: "https://www.creapiks.net/BlindTest/55.mp3",
    album: "5",
  },
  {
    songIndex: "56",
    songName: "Reviens",
    mp3: "https://www.creapiks.net/BlindTest/56.mp3",
    album: "5",
  },
  {
    songIndex: "57",
    songName: "On la tire içi",
    mp3: "https://www.creapiks.net/BlindTest/57.mp3",
    album: "5",
  },
  {
    songIndex: "58",
    songName: "Elle danse",
    mp3: "https://www.creapiks.net/BlindTest/58.mp3",
    album: "5",
  },
  {
    songIndex: "59",
    songName: "Hey baybay ",
    mp3: "https://www.creapiks.net/BlindTest/59.mp3",
    album: "5",
  },
  {
    songIndex: "60",
    songName: "I love U so much",
    mp3: "https://www.creapiks.net/BlindTest/60.mp3",
    album: "5",
  },
  {
    songIndex: "61",
    songName: "Cliquer comme un con",
    mp3: "https://www.creapiks.net/BlindTest/61.mp3",
    album: "5",
  },
  {
    songIndex: "62",
    songName: "On est le monde",
    mp3: "https://www.creapiks.net/BlindTest/62.mp3",
    album: "5",
  },
  {
    songIndex: "63",
    songName: "Comptez sur moi",
    mp3: "https://www.creapiks.net/BlindTest/63.mp3",
    album: "5",
  },
  {
    songIndex: "64",
    songName: "Les futurs parents",
    mp3: "https://www.creapiks.net/BlindTest/64.mp3",
    album: "5",
  },
  {
    songIndex: "65",
    songName: "Le plus grand des bonheurs",
    mp3: "https://www.creapiks.net/BlindTest/65.mp3",
    album: "5",
  },
  {
    songIndex: "66",
    songName: "Latino Latina",
    mp3: "https://www.creapiks.net/BlindTest/66.mp3",
    album: "5",
  },
  {
    songIndex: "67",
    songName: "Bon voyage",
    mp3: "https://www.creapiks.net/BlindTest/67.mp3",
    album: "5",
  },
];
