export const songs = [
  {
    identifiant: "1",
    titre: "Et c'est pour ca",
    mp3: "assets/1.mp3",
    album: "1",
  },
  {
    identifiant: "2",
    titre: "La tartiflette",
    mp3: "assets/2.mp3",
    album: "1",
  },
  {
    identifiant: "3",
    titre: "Les routes de Nantes",
    mp3: "assets/3.mp3",
    album: "1",
  },
  {
    identifiant: "4",
    titre: "Arthur",
    mp3: "assets/4.mp3",
    album: "1",
  },
  {
    identifiant: "5",
    titre: "Je suis moche",
    mp3: "assets/5.mp3",
    album: "1",
  },
  {
    identifiant: "6",
    titre: "Je te trouve tellement jolie",
    mp3: "assets/6.mp3",
    album: "1",
  },

  {
    identifiant: "7",
    titre: "Le Père Noel",
    mp3: "assets/7.mp3",
    album: "1",
  },
  {
    identifiant: "8",
    titre: "Que j'aime tes fesses",
    mp3: "assets/8.mp3",
    album: "1",
  },
  {
    identifiant: "9",
    titre: "Mon rêve",
    mp3: "assets/9.mp3",
    album: "1",
  },
  {
    identifiant: "10",
    titre: "Tu pues la crotte",
    mp3: "assets/10.mp3",
    album: "1",
  },
  {
    identifiant: "11",
    titre: "Le ver",
    mp3: "assets/11.mp3",
    album: "1",
  },
  {
    identifiant: "12",
    titre: "La cousine",
    mp3: "assets/12.mp3",
    album: "1",
  },
  {
    identifiant: "13",
    titre: "J'aime pas la viande cuite",
    mp3: "assets/13.mp3",
    album: "1",
  },
  {
    identifiant: "14",
    titre: "Heavy Metal",
    mp3: "assets/14.mp3",
    album: "1",
  },

  {
    identifiant: "15",
    titre: "Cheese Powers",
    mp3: "assets/15.mp3",
    album: "2",
  },
  {
    identifiant: "16",
    titre: "De Cannes à Nice",
    mp3: "assets/16.mp3",
    album: "2",
  },
  {
    identifiant: "17",
    titre: "Sombre héros",
    mp3: "assets/17.mp3",
    album: "2",
  },
  {
    identifiant: "18",
    titre: "Anal Satellite",
    mp3: "assets/18.mp3",
    album: "2",
  },
  {
    identifiant: "19",
    titre: "Emmène-moi là-bas",
    mp3: "assets/19.mp3",
    album: "2",
  },
  {
    identifiant: "20",
    titre: "Ma botte au cul",
    mp3: "assets/20.mp3",
    album: "2",
  },
  {
    identifiant: "21",
    titre: "La Ferme",
    mp3: "assets/21.mp3",
    album: "2",
  },
  {
    identifiant: "22",
    titre: "Ma cigarette",
    mp3: "assets/22.mp3",
    album: "2",
  },
  {
    identifiant: "23",
    titre: "La Wave Attitude",
    mp3: "assets/23.mp3",
    album: "2",
  },
  {
    identifiant: "24",
    titre: "J'ai une histoire triste",
    mp3: "assets/24.mp3",
    album: "2",
  },
  {
    identifiant: "25",
    titre: "Je mange déséquilibré",
    mp3: "assets/25.mp3",
    album: "2",
  },
  {
    identifiant: "26",
    titre: "Marie",
    mp3: "assets/26.mp3",
    album: "2",
  },
  {
    identifiant: "27",
    titre: "Ma raison d'être",
    mp3: "assets/27.mp3",
    album: "2",
  },

  {
    identifiant: "28",
    titre: "Ça nous saoule",
    mp3: "assets/28.mp3",
    album: "3",
  },
  {
    identifiant: "29",
    titre: "Lettre à Michelle",
    mp3: "assets/29.mp3",
    album: "3",
  },
  {
    identifiant: "30",
    titre: "BB Rockers",
    mp3: "assets/30.mp3",
    album: "3",
  },
  {
    identifiant: "31",
    titre: "J'ai un bon copain",
    mp3: "assets/31.mp3",
    album: "3",
  },
  {
    identifiant: "32",
    titre: "Trouvez-vous ça bien",
    mp3: "assets/32.mp3",
    album: "3",
  },
  {
    identifiant: "33",
    titre: "La galère d'un pirate",
    mp3: "assets/33.mp3",
    album: "3",
  },
  {
    identifiant: "34",
    titre: "Et à la fin.",
    mp3: "assets/34.mp3",
    album: "3",
  },
  {
    identifiant: "35",
    titre: "La base virale",
    mp3: "assets/35.mp3",
    album: "3",
  },
  {
    identifiant: "36",
    titre: "À la chasse",
    mp3: "assets/36.mp3",
    album: "3",
  },
  {
    identifiant: "37",
    titre: "Allons chez toi",
    mp3: "assets/37.mp3",
    album: "3",
  },
  {
    identifiant: "38",
    titre: "Une histoire formidable",
    mp3: "assets/38.mp3",
    album: "3",
  },
  {
    identifiant: "39",
    titre: "Nirvanoir",
    mp3: "assets/39.mp3",
    album: "3",
  },
  {
    identifiant: "40",
    titre: "Car tu es",
    mp3: "assets/40.mp3",
    album: "3",
  },

  {
    identifiant: "41",
    titre: "L'amour de la musique",
    mp3: "assets/41.mp3",
    album: "4",
  },
  {
    identifiant: "42",
    titre: "Babos à la Playa",
    mp3: "assets/42.mp3",
    album: "4",
  },
  {
    identifiant: "43",
    titre: "Je suis covoiturage",
    mp3: "assets/43.mp3",
    album: "4",
  },
  {
    identifiant: "44",
    titre: "C'est pas punk",
    mp3: "assets/44.mp3",
    album: "4",
  },
  {
    identifiant: "45",
    titre: "Ça plane pour moi",
    mp3: "assets/45.mp3",
    album: "4",
  },
  {
    identifiant: "46",
    titre: "Bienvenue à bord",
    mp3: "assets/46.mp3",
    album: "4",
  },
  {
    identifiant: "47",
    titre: "Beauf de France",
    mp3: "assets/47.mp3",
    album: "4",
  },
  {
    identifiant: "48",
    titre: "Génération 90's",
    mp3: "assets/48.mp3",
    album: "4",
  },
  {
    identifiant: "49",
    titre: "Subjectif",
    mp3: "assets/49.mp3",
    album: "4",
  },
  {
    identifiant: "50",
    titre: "Cougar",
    mp3: "assets/50.mp3",
    album: "4",
  },
  {
    identifiant: "51",
    titre: "Escuala mi amor",
    mp3: "assets/51.mp3",
    album: "4",
  },
  {
    identifiant: "52",
    titre: "La nouvelle star",
    mp3: "assets/52.mp3",
    album: "4",
  },
  {
    identifiant: "53",
    titre: "J'te tire",
    mp3: "assets/53.mp3",
    album: "4",
  },
  {
    identifiant: "54",
    titre: "Bonus 8 bits",
    mp3: "assets/54.mp3",
    album: "4",
  },

  {
    identifiant: "55",
    titre: "Ouvre les yeux",
    mp3: "assets/55.mp3",
    album: "5",
  },
  {
    identifiant: "56",
    titre: "Reviens",
    mp3: "assets/56.mp3",
    album: "5",
  },
  {
    identifiant: "57",
    titre: "On la tire içi",
    mp3: "assets/57.mp3",
    album: "5",
  },
  {
    identifiant: "58",
    titre: "Elle danse",
    mp3: "assets/58.mp3",
    album: "5",
  },
  {
    identifiant: "59",
    titre: "Hey baybay ",
    mp3: "assets/59.mp3",
    album: "5",
  },
  {
    identifiant: "60",
    titre: "I love U so much",
    mp3: "assets/60.mp3",
    album: "5",
  },
  {
    identifiant: "61",
    titre: "Cliquer comme un con",
    mp3: "assets/61.mp3",
    album: "5",
  },
  {
    identifiant: "62",
    titre: "On est le monde",
    mp3: "assets/62.mp3",
    album: "5",
  },
  {
    identifiant: "63",
    titre: "Comptez sur moi",
    mp3: "assets/63.mp3",
    album: "5",
  },
  {
    identifiant: "64",
    titre: "Les futurs parents",
    mp3: "assets/64.mp3",
    album: "5",
  },
  {
    identifiant: "65",
    titre: "Le plus grand des bonheurs",
    mp3: "assets/65.mp3",
    album: "5",
  },
  {
    identifiant: "66",
    titre: "Latino Latina",
    mp3: "assets/66.mp3",
    album: "5",
  },
  {
    identifiant: "67",
    titre: "Bon voyage",
    mp3: "assets/67.mp3",
    album: "5",
  },
];
